### ISSUE TITLE
How can I view Vite daemon output?

### ISSUE THREAD

**Issue by robzor** [vigetlabs/craft-site-starter#87]
Hi there, 

I'm pretty new to DDEV and Vite and I can't for the life of me work out how to see the output of the Vite daemon in DDEV, which is especially useful for error messages in my css/js.

Currently i'm having to use `ddev logs` repeatedly. 

I thought `ddev ssh --service vite` would potentially work, but no dice. 

How are you guys handling Vite output errors?

**Comment by maxfenton** [comment]
@robzor 

tldr: comment out the `web_extra_daemons` section of `.ddev/config.yaml` and run those command steps in `hooks.post-start`

---

Depending on the state of a project, you might need to temporarily (or permanently) change the `.ddev/config.yaml` from something like 
```
hooks:
  post-start:
    - composer: install
    - exec: "php craft up"
web_extra_daemons:
  # Run vite in a separate process
  - name: 'vite'
    command: 'npm install && npm run build && npm run dev'
    directory: /var/www/html
```

to

```
hooks:
  post-start:
    - composer: install
    - exec: "php craft up"
    - exec: "npm install"
    - exec: "npm run build"
    - exec: "npm run dev"
# web_extra_daemons:
  # Run vite in a separate process
# - name: 'vite'
#   command: 'npm install && npm run build && npm run dev'
#   directory: /var/www/html
```

That's a change that I make when something is in more active development and it will show the running state of Vite in the terminal window you use for `ddev start` 

Maybe this repo could have _both_ of those approaches in the config, with one commented out.
